config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  namespace :answers do
    resources :wrongs, only: :show
    resources :corrects, only: :show
    resources :checks, only: :create
  end

  root to: 'home#index'
  resources :exercises, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :exercise

  enum kind: { default: 0, sql: 1, active_record: 2 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :exercises
end

app/models/city.rb
class City < ApplicationRecord
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  with_options presence: true do
    validates :title
    validates :sql
    validates :active_record_query
  end

  belongs_to :category

  before_save :set_sql

  # ar_sql => "Exercise.all" 文字列で渡ってくる
  # table_name => exercises
  # table_name.classify.constantize => Exercise
  # table_name.constantize.class_eval(string_activerecord_query)
  def check?(string_activerecord_query)
    ar_query = generate_sql_by_acitive_record_query(string_activerecord_query)
    return '不正なコードです' unless ar_query
    if sql == ar_query
      true
    else
      ar_query
    end

    # find, find_by使うとactive_record_relationで返ってこない
    # 返ってくるレコードが同じか判定したい場合は、↓コードを使う
    # if activerecord_relation.respond_to?(:to_a)
    #   activerecord_relation = activerecord_relation.to_a
    # else
    #   activerecord_relation = [activerecord_relation]
    # end
    # sql == activerecord_relation
  end

  private

  def model_class
    table_name.classify.constantize
  end

  def model_class_class_eval(string)
    model_class.readonly.class_eval(string)
  end

  def respond_to_to_sql?(string)
    model_class_class_eval(string).respond_to?(:to_sql)
  end

  def generate_sql_by_acitive_record_query(string)
    return unless respond_to_to_sql?(string)
    model_class_class_eval(string).to_sql
  end

  def set_sql
    self.sql = generate_sql_by_acitive_record_query(active_record_query)
  end
end

app/models/money_book.rb
class MoneyBook < ApplicationRecord
end

app/models/station.rb
class Station < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.avatar = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/answers/checks_controller.rb
class Answers::ChecksController < ApplicationController
  def create
    @exercise = Exercise.find(params[:exercise_id])
    begin
      answer = @exercise.check?(params[:answer])
    # syntax errorも捕捉したいのでExceptionクラスを指定
    rescue => e
      return redirect_to answers_wrong_path(@exercise, answer: e)
      logger.fatal e
    rescue Exception => e
      logger.fatal e
      return redirect_to answers_wrong_path(@exercise, answer: e)
    end
    if answer == true
      redirect_to answers_correct_path(@exercise)
    else
      redirect_to answers_wrong_path(@exercise, answer: answer)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]

  # GET /exercises
  # GET /exercises.json
  def index
    @exercises = Exercise.order(:id).page(params[:page])
  end

  # GET /exercises/1
  # GET /exercises/1.json
  def show
  end

  # GET /exercises/new
  def new
    @exercise = Exercise.new
  end

  # GET /exercises/1/edit
  def edit
  end

  # POST /exercises
  # POST /exercises.json
  def create
    @exercise = Exercise.new(exercise_params)

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to @exercise, notice: 'Exercise was successfully created.' }
        format.json { render :show, status: :created, location: @exercise }
      else
        format.html { render :new }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercises/1
  # PATCH/PUT /exercises/1.json
  def update
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to @exercise, notice: 'Exercise was successfully updated.' }
        format.json { render :show, status: :ok, location: @exercise }
      else
        format.html { render :edit }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercises/1
  # DELETE /exercises/1.json
  def destroy
    @exercise.destroy
    respond_to do |format|
      format.html { redirect_to exercises_url, notice: 'Exercise was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercise
      @exercise = Exercise.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exercise_params
      params.require(:exercise).permit(:title, :body, :answer)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/answers/check_helper.rb
module Answers::CheckHelper
end

app/helpers/answers/corrects_helper.rb
module Answers::CorrectsHelper
end

app/helpers/answers/wrongs_helper.rb
module Answers::WrongsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/check_answers_helper.rb
module CheckAnswersHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/    U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="    sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <!-- Begin page content -->
    <div class="container">
      <%= yield %>
    </div>

    <footer class="footer">
      <div class="container">
        <span class="text-muted">2017 ORM TRAINING APP</span>
      </div>
    </footer>
  </body>
</html>

app/views/shared/_navbar.html.erb
    <!-- Fixed navbar -->
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#">ORM100本ノック</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to '問題一覧', exercises_path, class: 'nav-link' %>
      </li>
<!--       <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li> -->
    </ul>
<!--     <form class="form-inline mt-2 mt-md-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> -->
  </div>
</nav>